services:

  products-db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile

  products-api:
    build:
      context: ../
      dockerfile: docker/products-api/Dockerfile

  stock-api:
    build:
      context: ../
      dockerfile: docker/stock-api/Dockerfile

  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile